version: "3"
services:
  # app:
  #   restart: always
  #   ports:
  #     - "8080:3000"
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #   depends_on:
  #     - db
  #     - soketi
  #   networks:
  #     - rtm
  soketi:
    image: "quay.io/soketi/soketi:1.6-16-distroless"
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      SOKETI_DEBUG: "0"
      SOKETI_METRICS_ENABLED: "true"
      SOKETI_METRICS_PROMETHEUS_PREFIX: "rtm_"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_APP_MANAGER_DRIVER: "dynamodb"
      SOKETI_APP_MANAGER_CACHE_ENABLED: "true"
      SOKETI_APP_MANAGER_CACHE_TTL: 120
      SOKETI_APP_MANAGER_DYNAMODB_TABLE: "realtime_apps"
      SOKETI_APP_MANAGER_DYNAMODB_REGION: "eu-west-2"
    ports:
      - "80:6001"
      - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
